[pytest]
addopts =
    --capture=no
    --cov=kotti
    --cov-config .coveragerc
    --cov-report=term-missing
    --doctest-modules
    --doctest-glob='*.txt'
    --ignore=kotti/templates/
#    --pep8
    --strict
    --tb=native
    --travis-fold=auto
    kotti/tests
python_files = test_*.py
pep8ignore = E501 E122 E123 E125 E128 E711 E713 E714 E402
markers =
    user: mark test to be run as the given user
    slow: mark test to be run only with --runslow option
